export const ADD_ARTICULO = 'ADD ARTICULO'
export const DELETE_ARTICULO = 'DELETE ARTICULO'
export const MOSTRAR_FORMULARIO = 'MOSTRAR FORMULARIO'
export const ESCONCER_FORMULARIO = 'ESCONDER FORMULARIO'